apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  cinder: 
    volumeID: 4db7ea4a-14e8-4738-ad9b-115b92d19b27
    fsType: ext4
