kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cinder-storage-pvc
  annotations: {
    volume.beta.kubernetes.io/storage-class: cinder-storage
  }
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
