kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: cinder-storage
  annotations:                                          
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/cinder
parameters:
  #type: fast
  availability: nova
