apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-path
spec:
  rules:
     - http:
        paths:
        - path: /nginx
          backend:
            serviceName: nginx-test-path
            servicePort: 80
