apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vhost-test-vhost
spec:
  rules:
  - host: nginx-vhost.kycloud-k8s-1.com
    http:
      paths:
      - backend:
          serviceName: nginx-test-vhost
          servicePort: 8088

