apiVersion: v1
kind: Service
metadata:
  name: nginx-test-vhost
spec:
  ports:
    - port: 8088
      targetPort: 80
  selector:
    app: nginx-test-vhost
apiVersion: v1

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-test-vhost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-test-vhost
    spec:
      containers:
      - name: nginx-test-vhost
        image: daocloud.io/library/nginx
        ports:
        - containerPort: 80
